# Site settings
title: dvagribank
email: email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: ""
footer_copy: All right reserved.

cover: cover_image # hình ảnh mặc định hiển thị thay cho slideshow nếu không được định nghĩa trong trang.


# Build settings
markdown: kramdown
